name: Build Frontend

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label:
          - "movies"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  #latest is @v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: |
          npm install

      - name: Build Frontend
        working-directory: frontend
        run: |
          # Add any build commands for your Next.js frontend
          npm run build